// Exports:
export const INTERNAL_MESSAGE_ACTIONS = {
  fetchBlocklistsMapFromRemote: 'fetchBlocklistsMapFromRemote',
  generateAndUpdateUnifiedBlocklist: 'generateAndUpdateUnifiedBlocklist',
  getBlocklistPreferences: 'getBlocklistPreferences',
  setBlocklistPreferences: 'setBlocklistPreferences',
  getBlocklistHashes: 'getBlocklistHashes',
  setBlocklistHash: 'setBlocklistHash',
  getBlocklist: 'getBlocklist',
  setBlocklist: 'setBlocklist',
  getBlocklistsMap: 'getBlocklistsMap',
  setBlocklistsMap: 'setBlocklistsMap',
  getUnifiedBlocklist: 'getUnifiedBlocklist',
  setUnifiedBlocklist: 'setUnifiedBlocklist',
  refreshUnifiedBlocklist: 'refreshUnifiedBlocklist',
  getScannedTweetCount: 'getScannedTweetCount',
  incrementScannedTweetCount: 'incrementScannedTweetCount',
  refreshScannedTweetCount: 'refreshScannedTweetCount',
  getRemovedTweetCount: 'getRemovedTweetCount',
  incrementRemovedTweetCount: 'incrementRemovedTweetCount',
  refreshRemovedTweetCount: 'refreshRemovedTweetCount',
  getCurrentSessionUsername: 'getCurrentSessionUsername',
  setCurrentSessionUsername: 'setCurrentSessionUsername',
  refreshCurrentSessionUsername: 'refreshCurrentSessionUsername',
  getIsCurrentSessionUserBlocked: 'getIsCurrentSessionUserBlocked',
  setIsCurrentSessionUserBlocked: 'setIsCurrentSessionUserBlocked',
  refreshIsCurrentSessionUserBlocked: 'refreshIsCurrentSessionUserBlocked',
} as const
